export const LOAD_DATA='LOAD_DATA';
export const LOAD_DATA_FAILED='LOAD_DATA_FAILED';

export const ADD_INGREDIENTS='ADD_INGREDIENTS';
export const REMOVE_INGREDIENCE='REMOVE_INGREDIENCE';
export const UPDATE_PURCHASABLE='UPDATE_PURCHASABLE';

export const ORDER_STARTED='ORDER_STARTED';
export const ORDER_SUCCESS='ORDER_SUCCESS';
export const ORDER_FAILED='ORDER_FAILED';

export const FETCH_ORDERS_START='FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCEED='FETCH_ORDERS_SUCCEED';
export const FETCH_ORDERS_FAILED='FETCH_ORDERS_FAILED';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCEED='AUTH_SUCCEED';
export const AUTH_FAILED='AUTH_FAILED';
export const AUTH_LOGOUT='AUTH_LOGOUT'

export const SET_AUTH_REDIRECT='SET_AUTH_REDIRECT'

